Repository Neograaph/ressources_relationnelles, pull requests merged in 2023-02, with the labels that each got.

#15 Ajout controller
  ApiCube/ApiCube/ApiCube.csproj
  ApiCube/ApiCube/Controllers/ActionTypesController.cs
  ApiCube/ApiCube/Controllers/AdressesController.cs
  ApiCube/ApiCube/Controllers/AimersController.cs
  ApiCube/ApiCube/Controllers/CommentairesController.cs
  ApiCube/ApiCube/Controllers/ConsultersController.cs
  ApiCube/ApiCube/Controllers/DocumentsController.cs
  ApiCube/ApiCube/Controllers/ModererComsController.cs
  ApiCube/ApiCube/Controllers/ModererResController.cs
  ApiCube/ApiCube/Controllers/RecherchersController.cs
  ApiCube/ApiCube/Controllers/WeatherForecastController.cs
  ApiCube/ApiCube/Models/BuisnessObjects/Relation.cs
  ApiCube/ApiCube/Models/BuisnessObjects/Utilisateur.cs
  ApiCube/ApiCube/WeatherForecast.cs
Labels: back

#17 16 ajout de tailwind
  Front/angular.json
  Front/package-lock.json
  Front/package.json
  Front/src/app/app.component.html
  Front/src/app/app.module.ts
  Front/src/app/composants/navbar/navbar.component.css
  Front/src/app/composants/navbar/navbar.component.html
  Front/src/app/composants/navbar/navbar.component.spec.ts
  Front/src/app/composants/navbar/navbar.component.ts
  Front/src/app/services/ressource.service.spec.ts
  Front/src/app/services/ressource.service.ts
  Front/src/environments/environment.prod.ts
  Front/src/environments/environment.ts
  Front/src/styles.css
  Front/tailwind.config.js
  package-lock.json
Labels: front

#18 [FUNC] Accept Cors+Service angular
  ApiCube/ApiCube/Models/BuisnessObjects/Relation.cs
  ApiCube/ApiCube/Program.cs
  Front/package-lock.json
  Front/src/app/app.component.html
  Front/src/app/app.module.ts
  Front/src/app/composants/navbar/navbar.component.ts
  Front/src/app/services/actions-type.service.spec.ts
  Front/src/app/services/actions-type.service.ts
  Front/src/environments/environment.prod.ts
  Front/src/environments/environment.ts
Labels: back, front

#19 [FUNC] controller +3 manque juste relation
  ApiCube/ApiCube/Controllers/RessourcesController.cs
  ApiCube/ApiCube/Controllers/UtilisateursController.cs
Labels: back

#20 Create codeql.yml
  .github/workflows/codeql.yml
Labels: back, front

#21 Controler add
  ApiCube/ApiCube/Controllers/RelationsController.cs
  ApiCube/ApiCube/Controllers/UtilisateursController.cs
  ApiCube/ApiCube/Migrations/20230217140026_init.Designer.cs
  ApiCube/ApiCube/Migrations/20230217140026_init.cs
  ApiCube/ApiCube/Migrations/AppContexteModelSnapshot.cs
  ApiCube/ApiCube/Models/AppContexte.cs
  ApiCube/ApiCube/Models/BuisnessObjects/Adresse.cs
  ApiCube/ApiCube/Models/BuisnessObjects/Relation.cs
  ApiCube/ApiCube/Models/BuisnessObjects/Utilisateur.cs
Labels: back
